apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort # Changer LoadBalancer en NodePort
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080 # Facultatif, sinon Kubernetes assigne un port automatique
