name: Deploy Helm Chart

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: "latest"

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: "latest"

      - name: Configure Kubernetes Context
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig
          export KUBECONFIG=kubeconfig

      - name: Deploy Helm Chart
        run: |
          helm upgrade --install my-nginx C:\Users\morta\OneDrive\Documents\GitHub\kubernetes-practice-projects\Helm\my-nginx --debug

